version: '3.8'

services:
  db:
    image: postgres:15
    container_name: geospatial_db_container
    restart: always
    environment:
      - POSTGRES_DB=geospatial_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sua_senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: